### PR TITLE
updating content

### PR DESCRIPTION
**Pull request by sonyamann**
I think I'm doing this right but I constantly forget how PRs work so I may insta-close this and make another one ahhhhhh

### CODE REVIEW

**Comment by sonyamann** [comment]
@RichardLitt can you give me permissions to resolve conflicts, I'd prefer to do it myself if you don't mind

**Comment by RichardLitt** [comment]
You should be able to see your link here: https://github.com/RichardLitt/zcashfoundation.github.io/invitations. (Sent in email, too, but the link doesn't need to be private to you, so this comment should be fine).

**Comment by sonyamann** [comment]
@RichardLitt I remember why I stalled out on this:
screen shot 2018-12-04 at 4 38 15 pm

Do you mind resolving those conflicts? (I'm still scared of CLI git, heh)

**Comment by RichardLitt** [comment]
@sonyamann Check out https://github.com/RichardLitt/zcashfoundation.github.io/pull/30. :)

**Pull request closed without merging**
