### PR TITLE
syncing content

### PR DESCRIPTION
**Pull request by sonyamann**

### CODE REVIEW

**Comment by sonyamann** [comment]
@RichardLitt I'm getting the same thing where I can't update all the content and go through merge issues with content on the website because of config files, etc, and I don't know why? I thought #30 fixed that. Am I misunderstanding something about the process? (That seems most likely to me since my mental model of git is still... faulty.)

screen shot 2018-12-07 at 4 37 59 pm

**Comment by RichardLitt** [comment]
I'm sorry! I've been looking at this, and it's really hard for me to figure out what commits you're adding. I see two extra commits from Josh, but nothing different from you since #30.

Can you please check out `RichardLitt/master` and apply content edits there, and `RichardLitt/gh-pages` to apply edits for the website? The main issue is that you're still using the old origin - `zcashfoundation/master` - but I've made substantial changes since then. 

Happy to jump on a call and figure this out. Let me know if that would help.

**Comment by sonyamann** [comment]
Ahhh I bet that's the problem, wrong branch.

**Comment by sonyamann** [comment]
Okay I'm still confused :0
Getting the same error here: https://github.com/RichardLitt/zcashfoundation.github.io/pull/32

What I want to do: Bring content (blog posts, etc.) from our current website repo into this one, so that they are up to date with each other.

At this point I feel like I should have you do it @RichardLitt because clearly I am not understanding something

If you think the best resolution would be going over it on a phone call, I'm good with that! Monday?

**Comment by RichardLitt** [comment]
All of that content is already here. I don't think you're adding anything new - just, the commits look different because I cleaned it up in https://github.com/RichardLitt/zcashfoundation.github.io/pull/30/files. Take a look at https://github.com/RichardLitt/zcashfoundation.github.io/pull/30/files and see if there is any different content you want to bring over - for now, I am pretty sure you have everything. 

Make sense?

Monday works for me, too. When works for you?

**Comment by RichardLitt** [comment]
Closed in #30.

**Pull request closed without merging**
